# Copy this to .pre-commit-config.yaml and edit as needed

repos:
  - repo: local
    hooks:
      - id: composer-format
        name: Format PHP
        description: Formats PHP files with `composer run format`
        entry: composer run format
        language: system
        types: [ php ]

      - id: composer-analyze-mago
        name: Analyze PHP
        description: Analyzes PHP files with `composer run mago analyze`
        entry: composer run mago analyze
        language: system
        types: [ php ]
