<?php
/**
 * UpdateOfferPackagesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenWPAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenWP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenWPAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateOfferPackagesTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateOfferPackages
 * @package     OpenWPAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateOfferPackagesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateOfferPackages"
     */
    public function testUpdateOfferPackages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "full"
     */
    public function testPropertyFull()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "no_content"
     */
    public function testPropertyNoContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "new_bundled"
     */
    public function testPropertyNewBundled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "partial"
     */
    public function testPropertyPartial()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rollback"
     */
    public function testPropertyRollback()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
