<?php
/**
 * PluginOffer
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenWPAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenWP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenWPAPI\Model;

use \ArrayAccess;
use \OpenWPAPI\ObjectSerializer;

/**
 * PluginOffer Class Doc Comment
 *
 * @category Class
 * @package  OpenWPAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PluginOffer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PluginOffer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'slug' => 'string',
        'plugin' => 'string',
        'new_version' => 'string',
        'url' => 'string',
        'package' => 'string',
        'icons' => 'array<string,string>',
        'banners' => 'array<string,string>',
        'banners_rtl' => 'string[]',
        'requires' => 'string',
        'tested' => 'string',
        'requires_php' => 'string',
        'requires_plugins' => 'string[]',
        'compatibility' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'slug' => null,
        'plugin' => null,
        'new_version' => null,
        'url' => null,
        'package' => null,
        'icons' => null,
        'banners' => null,
        'banners_rtl' => null,
        'requires' => null,
        'tested' => null,
        'requires_php' => null,
        'requires_plugins' => null,
        'compatibility' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'slug' => false,
        'plugin' => false,
        'new_version' => false,
        'url' => false,
        'package' => true,
        'icons' => true,
        'banners' => true,
        'banners_rtl' => true,
        'requires' => true,
        'tested' => true,
        'requires_php' => true,
        'requires_plugins' => true,
        'compatibility' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'slug' => 'slug',
        'plugin' => 'plugin',
        'new_version' => 'new_version',
        'url' => 'url',
        'package' => 'package',
        'icons' => 'icons',
        'banners' => 'banners',
        'banners_rtl' => 'banners_rtl',
        'requires' => 'requires',
        'tested' => 'tested',
        'requires_php' => 'requires_php',
        'requires_plugins' => 'requires_plugins',
        'compatibility' => 'compatibility'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'slug' => 'setSlug',
        'plugin' => 'setPlugin',
        'new_version' => 'setNewVersion',
        'url' => 'setUrl',
        'package' => 'setPackage',
        'icons' => 'setIcons',
        'banners' => 'setBanners',
        'banners_rtl' => 'setBannersRtl',
        'requires' => 'setRequires',
        'tested' => 'setTested',
        'requires_php' => 'setRequiresPhp',
        'requires_plugins' => 'setRequiresPlugins',
        'compatibility' => 'setCompatibility'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'slug' => 'getSlug',
        'plugin' => 'getPlugin',
        'new_version' => 'getNewVersion',
        'url' => 'getUrl',
        'package' => 'getPackage',
        'icons' => 'getIcons',
        'banners' => 'getBanners',
        'banners_rtl' => 'getBannersRtl',
        'requires' => 'getRequires',
        'tested' => 'getTested',
        'requires_php' => 'getRequiresPhp',
        'requires_plugins' => 'getRequiresPlugins',
        'compatibility' => 'getCompatibility'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('plugin', $data ?? [], null);
        $this->setIfExists('new_version', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('package', $data ?? [], null);
        $this->setIfExists('icons', $data ?? [], null);
        $this->setIfExists('banners', $data ?? [], null);
        $this->setIfExists('banners_rtl', $data ?? [], null);
        $this->setIfExists('requires', $data ?? [], null);
        $this->setIfExists('tested', $data ?? [], null);
        $this->setIfExists('requires_php', $data ?? [], null);
        $this->setIfExists('requires_plugins', $data ?? [], null);
        $this->setIfExists('compatibility', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID of the plugin for update purposes, should be a URI specified in the `Update URI` header field.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string|null
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string|null $slug Slug of the plugin.
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets plugin
     *
     * @return string|null
     */
    public function getPlugin()
    {
        return $this->container['plugin'];
    }

    /**
     * Sets plugin
     *
     * @param string|null $plugin The file path of the plugin.
     *
     * @return self
     */
    public function setPlugin($plugin)
    {
        if (is_null($plugin)) {
            throw new \InvalidArgumentException('non-nullable plugin cannot be null');
        }
        $this->container['plugin'] = $plugin;

        return $this;
    }

    /**
     * Gets new_version
     *
     * @return string|null
     */
    public function getNewVersion()
    {
        return $this->container['new_version'];
    }

    /**
     * Sets new_version
     *
     * @param string|null $new_version The new version of the plugin available for update.
     *
     * @return self
     */
    public function setNewVersion($new_version)
    {
        if (is_null($new_version)) {
            throw new \InvalidArgumentException('non-nullable new_version cannot be null');
        }
        $this->container['new_version'] = $new_version;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url The URL for details of the plugin.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets package
     *
     * @return string|null
     */
    public function getPackage()
    {
        return $this->container['package'];
    }

    /**
     * Sets package
     *
     * @param string|null $package Optional. The update ZIP for the plugin.
     *
     * @return self
     */
    public function setPackage($package)
    {
        if (is_null($package)) {
            array_push($this->openAPINullablesSetToNull, 'package');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('package', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['package'] = $package;

        return $this;
    }

    /**
     * Gets icons
     *
     * @return array<string,string>|null
     */
    public function getIcons()
    {
        return $this->container['icons'];
    }

    /**
     * Sets icons
     *
     * @param array<string,string>|null $icons Optional. Array of plugin icons with different resolutions.
     *
     * @return self
     */
    public function setIcons($icons)
    {
        if (is_null($icons)) {
            array_push($this->openAPINullablesSetToNull, 'icons');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('icons', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['icons'] = $icons;

        return $this;
    }

    /**
     * Gets banners
     *
     * @return array<string,string>|null
     */
    public function getBanners()
    {
        return $this->container['banners'];
    }

    /**
     * Sets banners
     *
     * @param array<string,string>|null $banners Optional. Array of plugin banners.
     *
     * @return self
     */
    public function setBanners($banners)
    {
        if (is_null($banners)) {
            array_push($this->openAPINullablesSetToNull, 'banners');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('banners', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['banners'] = $banners;

        return $this;
    }

    /**
     * Gets banners_rtl
     *
     * @return string[]|null
     */
    public function getBannersRtl()
    {
        return $this->container['banners_rtl'];
    }

    /**
     * Sets banners_rtl
     *
     * @param string[]|null $banners_rtl Optional. Array of plugin RTL banners.
     *
     * @return self
     */
    public function setBannersRtl($banners_rtl)
    {
        if (is_null($banners_rtl)) {
            array_push($this->openAPINullablesSetToNull, 'banners_rtl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('banners_rtl', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['banners_rtl'] = $banners_rtl;

        return $this;
    }

    /**
     * Gets requires
     *
     * @return string|null
     */
    public function getRequires()
    {
        return $this->container['requires'];
    }

    /**
     * Sets requires
     *
     * @param string|null $requires Optional. The minimum version of WordPress required for the plugin.
     *
     * @return self
     */
    public function setRequires($requires)
    {
        if (is_null($requires)) {
            array_push($this->openAPINullablesSetToNull, 'requires');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requires', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requires'] = $requires;

        return $this;
    }

    /**
     * Gets tested
     *
     * @return string|null
     */
    public function getTested()
    {
        return $this->container['tested'];
    }

    /**
     * Sets tested
     *
     * @param string|null $tested Optional. The version of WordPress the plugin is tested against.
     *
     * @return self
     */
    public function setTested($tested)
    {
        if (is_null($tested)) {
            array_push($this->openAPINullablesSetToNull, 'tested');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tested', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tested'] = $tested;

        return $this;
    }

    /**
     * Gets requires_php
     *
     * @return string|null
     */
    public function getRequiresPhp()
    {
        return $this->container['requires_php'];
    }

    /**
     * Sets requires_php
     *
     * @param string|null $requires_php Optional. The minimum version of PHP required for the plugin.
     *
     * @return self
     */
    public function setRequiresPhp($requires_php)
    {
        if (is_null($requires_php)) {
            array_push($this->openAPINullablesSetToNull, 'requires_php');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requires_php', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requires_php'] = $requires_php;

        return $this;
    }

    /**
     * Gets requires_plugins
     *
     * @return string[]|null
     */
    public function getRequiresPlugins()
    {
        return $this->container['requires_plugins'];
    }

    /**
     * Sets requires_plugins
     *
     * @param string[]|null $requires_plugins Optional. List of required plugins for this plugin.
     *
     * @return self
     */
    public function setRequiresPlugins($requires_plugins)
    {
        if (is_null($requires_plugins)) {
            array_push($this->openAPINullablesSetToNull, 'requires_plugins');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requires_plugins', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requires_plugins'] = $requires_plugins;

        return $this;
    }

    /**
     * Gets compatibility
     *
     * @return string[]|null
     */
    public function getCompatibility()
    {
        return $this->container['compatibility'];
    }

    /**
     * Sets compatibility
     *
     * @param string[]|null $compatibility Optional. List of compatibility data for this plugin.
     *
     * @return self
     */
    public function setCompatibility($compatibility)
    {
        if (is_null($compatibility)) {
            array_push($this->openAPINullablesSetToNull, 'compatibility');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('compatibility', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['compatibility'] = $compatibility;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


