# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images
name: Build container images

# Due to the need to cross-build the image for arm64 and the cache not working, this action is SLOW (15m+)
# Because of this, we're using a local build/push process, and leaving this action only manually triggered.

on:
  workflow_dispatch: ~

#  push:
#    branches: ['main']
#    tags: ['*']
#  release:
#    types: ['published']

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/webapp/Dockerfile
            image: ghcr.io/aspirepress/aspirecloud
          - dockerfile: ./docker/laravel-worker/Dockerfile
            image: ghcr.io/aspirepress/aspirecloud-worker

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}

# The official action is not capable of building for a different arch 🙄
#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#        with:
#          context: .
#          target: prod
#          platforms: 'linux/arm64'
#          file: ${{ matrix.dockerfile }}
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/arm64 \
            -f ${{ matrix.dockerfile }} \
            $(for tag in $(echo "$DOCKER_METADATA_OUTPUT_TAGS" | xargs); do echo " -t $tag"; done) \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .

# Attestation action doesn't work with our manual buildx step
#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v2
#        with:
#          subject-name: ${{ matrix.image }}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true

